export enum COMMAND {
    START = 'start',
    KANDINSKY = 'kandinsky',
    GIGA_CHAT = 'giga_chat',
    HELP = 'help',
    END_SCENE = 'end',
    EVENT = 'event',
    GET_CARDS = 'get_cards'
}

export enum SLASH_COMMAND {
    START = '/start',
    KANDINSKY = '/kandinsky',
    GIGA_CHAT = '/giga_chat',
    HELP = '/help',
    END_SCENE = '/end',
    EVENT = '/event',
    GET_CARDS = '/get_cards'
}

export enum GET_CARDS_LABELS {
    START = 'START',
    REQUEST = 'REQUEST',
    END = 'END'
}

export enum GIGA_LABELS {
    START = "START",
    CHANGE_ROLE = 'CHANGE_ROLE',
    QUESTION_PROMPT = 'QUESTION_PROMPT',
    WAIT_PROMPT = 'WAIT_PROMPT',
    WAIT_GEN = 'WAIT_GEN',
    WAIT_ROLE = 'WAIT_ROLE',
    PROMPT_ROLE = 'PROMPT_ROLE',
    PROMPT_TEXT = 'PROMPT_TEXT',
    CALL_KANDINSKY = 'CALL_KANDINSKY',
    END = 'EDN',
}

export enum KANDINSKY_LABELS {
    START = "START",
    WAIT_REQUEST = 'WAIT_REQUEST',
    WAIT_PROMPT = 'WAIT_PROMPT',
    WAIT_STYLE = 'WAIT_STYLE',
    WAIT_GEN = 'WAIT_GEN',
    PROMPT_TEXT = 'PROMPT_TEXT',
    PROMPT_STYLE = 'PROMPT_STYLE',
    CALL_GIGA = 'CALL_GIGA',
    END = 'END'
}

export enum EVENT_LABELS {
    START = 'START',
    CHOOSE_EVENT_THEME = 'CHOOSE_EVENT_THEME',
    WAIT_CHOOSE_THEME = 'WAIT_CHOOSE_THEME',
    WAIT_USER_ANSWER = 'WAIT_USER_ANSWER',
    CHOOSE_NAME = 'CHOOSE_NAME',
    WAIT_CHOOSE_NAME = 'WAIT_CHOOSE_NAME',
    WAIT_CHOOSE_NAME_ANSWER = 'WAIT_CHOOSE_NAME_ANSWER',
    START_PROMPT_TEXT = 'START_PROMPT_TEXT',
    WAIT_PROMPT_TEXT = 'WAIT_PROMPT_TEXT',
    WAIT_PROMPT_ANSWER = 'WAIT_PROMPT_ANSWER',
    GET_AI_RESPONSE = 'GET_AI_RESPONSE',
    CHOOSE_LOGIN = 'CHOOSE_LOGIN',
    WAIT_LOGIN = 'WAIT_LOGIN',
    WITH_ANONYMITY = 'WITH_ANONYMITY',
    WAIT_ANONYMITY_ANSWER = 'WAIT_ANONYMITY_ANSWER',
    SEND_REQUEST = 'SEND_REQUEST',
    WAIT_GENERATION = 'WAIT_GENERATION',
    END = 'END',
    PRE_PHONE = 'PRE_PHONE',
    PHONE = 'PHONE',
    PRE_LOGIN = 'PRE_LOGIN',
    LOGIN = 'LOGIN'
}

export enum SCENE {
    GIGA_CHAT = 'GIGA_CHAT',
    KANDINSKY = 'KANDINSKY',
    EVENT = 'EVENT',
    GET_CARDS = 'GET_CARDS',
    HOLD = 'HOLD'
}
